POST http://localhost:3001/accomodation-listing
Content-Type: application/json

{
  "title": "Cozy ",
  "description": "A comfortable and affordable hostel in a serene environment, perfect for students and professionals.",
  "locationType": "urban",
  "detailedLocation": "10 minutes from the city center, near Chancellor College",
  "gender": "unisex",
  "spaceAvailable": 12,
  "rentalFee": 45000,
  "bookingFee": 5000,
  "additionalFees": [
    "Electricity: MWK 2000 per month",
    "Water: MWK 1000 per month",
    "Internet: MWK 3000 per month"
  ]
}
