POST http://localhost:3000/auth/signup
content-type: application/json

{
  "firstName": "Dennis",
  "lastName": "zukwayo",
   "email" : "beatrice@gmail.com",
  "password" : "dennisojali",
  "phoneNumber": "+265888224603",
  "isOwner": false,
  "isAgent": false
}